import { FC } from "react";
import AppBar from "./app-bar";
import styles from "../styles/Home.module.css";
import Head from "next/head";

type Props = {
  title: string;
  extra?: any;
  children: JSX.Element;
  onSearch?: React.ChangeEventHandler<HTMLInputElement>;
};

const Layout: FC<Props> = ({ onSearch = () => {}, ...props }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar page={props.title} onChange={onSearch} />
      <main className={styles.main}>{props.children}</main>
      <footer className={styles.footer}>
        <a href={process.env.github} target="_blank" rel="noopener noreferrer">
          Developed by{" "}
          <span className={styles.author}>@{process.env.author}</span>
        </a>
      </footer>
    </div>
  );
};

export default Layout;
